-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 13:52:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `surname` VARCHAR(255) NULL,
  `staffcol` VARCHAR(45) NULL,
  `status` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price_count` DECIMAL(13,2) NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`, `staff_id`),
  INDEX `fk_sale_staff_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `description` VARCHAR(2500) NULL,
  `price` DECIMAL(10,2) NULL,
  `author_name` VARCHAR(155) NULL,
  `shelves` VARCHAR(255) NULL,
  `sales_id` INT NOT NULL,
  `sales_staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_books_sales1_idx` (`sales_id` ASC, `sales_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_sales1`
    FOREIGN KEY (`sales_id` , `sales_staff_id`)
    REFERENCES `mydb`.`sales` (`id` , `staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
